baseURL = 'https://imayakumar.com'
languageCode = 'en-us'
title = 'Imaya Kumar Jagannathan'
theme="hugo-sustain"


[params]
  avatar = "img/profile_imaya.jpeg"
  author = "Imaya Kumar Jagannathan"
  description = "Imaya's personal website"

[params.social]
  Github        = "awsimaya"
  #Twitter       = "imaya"
  LinkedIn      = "imaya"
  Threads       = "imayakumar"


